name: world_on_rails
channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - cudatoolkit=11.3.1
  - pip=21.2.2
  - python=3.7.9
  - pip:
    - dictor==0.1.9
    - imageio==2.16.0
    - imageio-ffmpeg==0.4.5
    - imgaug==0.4.0
    - lmdb==1.1.1
    - matplotlib==3.5.1
    - moviepy==1.0.3
    - numpy==1.21.5
    - opencv-python==4.5.5.62
    - py-trees==0.8.3
    - pygame==2.1.2
    - pyyaml==6.0
    - ray==1.11.0
    - shapely==1.8.0
    - tabulate==0.8.9
    - torch==1.10.2+cu113
    - torchaudio==0.10.2+cu113
    - torchvision==0.5.0
    - tqdm==4.62.3
    - wandb==0.12.10
    - xmlschema==1.9.2
